### ISSUE TITLE
Opening saved PassLok web app starts at blank page

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#10]
I saved the PassLok web app to my computer, to avoid having to pull a fresh copy each time that I use it (which is the second-best thing to using a signed browser extension).

When I open the saved app using Chromium Version 38.0 after a fresh browser restart, I see a blank page except for three tabs along the top (Main, Options, Help). Needless to say, this is not user-friendly. I can send a screen-shot if that would be helpful.

The javascript console has five entries referring to:
GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED VM116 www-embed-player.js:153mj VM116 www-embed-player.js:153lj VM116 www-embed-player.js:152pj VM116 www-embed-player.js:155oj VM116 www-embed-player.js:154Rk VM116 www-embed-player.js:206Co VM116 www-embed-player.js:310(anonymous function) VM116 www-embed-player.js:355(anonymous function) VM117 UxgrES_CGcg.html:9
GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILED VM116 www-embed-player.js:153
GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILED VM116 www-embed-player.js:153
GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED VM116 www-embed-player.js:153
GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED VM116 www-embed-player.js:153

This is related to my blocking of the embedded YouTube videos, as per Issue #3.

**Comment by fruiz500** [comment]
This is likely all related to the YouTube video embedded in the New User wizard, which is raised in another issue. I've made a test version with that removed, so you can test it. It is based on the v2.1.03 candidate (not yet on GitHub), which looks a little different. Here's the address:

https://passlok.com/test

**Comment by fruiz500** [comment]
Possibly this has been solved with version 2.1.03. Please check.
