### ISSUE TITLE
Clicking on "Main" tab leads to cached ciphertext that cannot be decrypted

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#11]
Starting out based on #10, I click on the "Main" tab on top.

I get to the Main tab, and see that the "Select Recipients" field only has "myself" listed, even through I entered other people previously (I'll file that issue separately). 

The main textarea contains some ciphertext from a previous session, I'm assuming (bear in mind that this is all after a browser restart). Clicking on "Lock/Unlock" does nothing.

**Comment by fruiz500** [comment]
I presume this has to do with issue #10. Please take a look a the test version at https://passlok.com/test and see if the problem is still there.

**Comment by fruiz500** [comment]
Possibly this has been solved with version 2.1.03. Please check.
