### ISSUE TITLE
Going straight to "MyLock" in new session leads to garbage names in selector

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#12]
Starting out as described in #10, I click on "MyLock", and then I get a pop-up dialog.

The top multi-selector lists the following names:
taltman
yt-remote-connected-devices
yt-remote-device-id
yt-remote-online-screens

Needless to say, only the first row is correct. The rest of the entries are garbage. 

Javascript log:
Uncaught secret Key needed VM52 PassLok%20privacy.html:6051readKey VM52 PassLok%20privacy.html:6051showLock VM52 PassLok%20privacy.html:6208

**Comment by fruiz500** [comment]
Possibly this has been solved with version 2.1.03. Please check.
