### ISSUE TITLE
Cannot Cancel out of MyLock pop-up dialog

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#13]
Starting from Issue #12, clicking on the "Cancel" button does nothing.

JavaScript console:
Uncaught TypeError: Cannot read property 'length' of undefined VM58 PassLok%20privacy.html:8888fillList VM58 PassLok%20privacy.html:8888cancelKey VM59 PassLok%20privacy.html:9236

**Comment by fruiz500** [comment]
Possibly this has been solved with version 2.1.03. Please check.
