### ISSUE TITLE
Unable to decrypt message

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#16]
Same browser set-up as before. Here's the JavaScript Console output (copying & pasting seems to mess up the formatting, if there's a better way to report this please let me know):

Uncaught RangeError: Maximum call stack size exceeded VM474 PassLok%20privacy.html:7621applyRScode VM474 PassLok%20privacy.html:7621Decrypt_single VM472 PassLok%20privacy.html:6880key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886key2any VM478 PassLok%20privacy.html:9612Decrypt_List VM472 PassLok%20privacy.html:7054Decrypt_single VM472 PassLok%20privacy.html:6886

**Comment by fruiz500** [comment]
Looks like it caught in an endless loop. Possibly having to do with issue #10 ?

**Comment by fruiz500** [comment]
Possibly this has been solved with version 2.1.03. Please check
