### ISSUE TITLE
Webapp version 2.3 vs app store version 2.2.8.3 (chrome) and Android (2.2.8)

### ISSUE THREAD

**Issue by ericogit** [fruiz500/PassLok-Privacy#18]
The versions in the Chrome app store and Google Play (2.2.8.*) differ from the Web-app (version 2.3)
Therefore messages sent between these version are not decryptable.

Update of the app store versions to version 2.3 might solve things?

**Comment by fruiz500** [comment]
Thanks for the heads up. Yes, we're moving slowly in getting the other
versions updated. The Chrome version should be updated today. Android soon
after.

You may also want to check out our new PassLok for Email extension, which
has just entered beta (hence the delays in the other version). It
integrates quite seamlessly with Chrome. Other webmail servers will be
added soon. You can't see it yet in the Chrome store, but here's the link:

https://chrome.google.com/webstore/detail/passlok-for-email/ehakihemolfjgbbfhkbjgahppbhecclh

On Sat, Apr 2, 2016 at 3:39 PM, ericogit notifications@github.com wrote:

> The versions in the Chrome app store and Google Play (2.2.8.*) differ from
> the Web-app (version 2.3)
> Therefore messages sent between these version are not decryptable.
> 
> Update of the app store versions to version 2.3 might solve things?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/fruiz500/passlok/issues/18

## 

Francisco Ruiz
Associate Professor
MMAE department
Illinois Institute of Technology

PL22ezLok=gqqjw-pq3eu-sgzpp-j87cn-fh7ik-6kvmn-comx2-b4xfn-gihga-s46e4=PL22ezLok
h**ps://www 'dot' youtube 'dot' com/watch?v=UOJXI8E0lKY

get the PassLok privacy app at: https://passlok.com http://passlok.com

**Comment by fruiz500** [comment]
Both the Chrome app and the GitHub version have been updated. Android is next.
