### ISSUE TITLE
Embedded YouTube videos enable PRISM tracking

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#3]
By enabling embedded YouTube videos in the PassLok app itself, YouTube can place nasty tracking cookies on your browser, and log every time that you access the PassLok app. This should be removed immediately. PassLok itself can link to a web page on the PassLok homepage, and have the homepage embed the videos for user convenience.

**Comment by fruiz500** [comment]
Good catch! I've wondering about this myself and now you've confirmed my suspicion. Now, there's only one embedded video (the rest are simple links, which open on a separate window), and this is in the New User wizard, which only gets loaded if the user clicks on "New User" at the start. Will putting this inside an iframe lessen the problem?

When you say the "PassLok homepage", what are you referring to? Right now, If you enter passlok.com on a browser, you get the app directly. Are you saying that the domain should point to something else?

**Comment by taltman** [comment]
What I meant by 'home page', was:

http://passlok.weebly.com/get-passlok.html

All PassLok documentation that requires interacting with third-parties should be exclusively on the home page, so that it's clear to the user that they are not using the App, but reading project documentation.

An iframe won't obscure the cookie, AFAICT. You really have to get rid of all third-party file/content loading from the App. Imagine if GnuPG sent a HTTP request to Microsoft or Google each time someone encrypted a message, which then installed a tracking cookie? That would be a scandal.

**Comment by fruiz500** [comment]
OK. After removing the embedded video (replaced with a link that opens on a separate window), the only iframes remaining are both to include www.passlok.com subdomains, which don't do any tracking AFAIK. The pages only load if a specific function referring to them is invoked.

There are also a number of links to instructional YouTube videos, all of which open on a separate tab or window. Are these also a liability?

**Comment by fruiz500** [comment]
The offending embedded video has been eliminated in version 2.1.03. The other video links include warnings so users are aware that their IPs may be leaked. The other pages loaded into iframes also contain warnings so users can cancel if they fear their IP anonymity might be jeopardized.
