### ISSUE TITLE
Lack of technical documentation

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#8]
Cryptographers reviewing PassLok, or doing a thorough audit of the design of PassLok, would need technical documentation aimed at an expert audience. Currently PassLok has a good amount of documentation aimed at a non-technical audience, but no technical documentation.

**Comment by fruiz500** [comment]
Good point. I've been working on a technical document covering PassLok under the hood, aimed at a level higher than the common user. The new version of PassLok has a link to it in the Help section. It can be found here:

http://passlok.weebly.com/uploads/2/4/1/8/24187628/passlok_technical_document.pdf
