### ISSUE TITLE
Suggested code reorganization

### ISSUE THREAD

**Issue by taltman** [fruiz500/PassLok-Privacy#9]
The following is a suggestion for how to change the organization of code in the git repository, to facilitate easier code development, auditing of existing code, all the while preserving the current work-level required for non-technical users to verify the PassLok web app.

The average end-user of PassLok is not going to inspect all 11k+ lines of JS code in PassLok.
  As far as the average end-user is concerned, they want to be able to verify the code-base (if even once), and have it load fast. 

  As far as a technical user or code reviewer is concerned, they want modularization so that they know which components to check, and which components are from trusted third parties, and don't need to be evaluated from scratch. For example, there's no need to review SJCL code if it is imported and unmodified. Or, if GUI code is separate from cryto-handling code, then there can be a separation of concerns, and code reviewers can focus on their area of expertise.

  This can be achieved by doing the following to the Git repo:
1. Split code into components (imported libraries, GUI code, cryto code, etc.)
2. Provide build script that will minimize/compress JS and concatenate into one HTML document.
3. Have build script put complete HTML document in "/bin" sub-directory
4. Provide hash of the HTML document and GPG-signature for hash
   
   Thus, the complete PassLok web app is still easy to deploy and verify for end-users (i.e., the hash checking is the same), but the modularization allows for easier auditing.
   Plus, the GPG signature allows for technical users to verify the codebase in terms of not just integrity, but authenticity. On that topic, if not being done already, all git commits should be cryptographically signed:

http://mikegerwitz.com/papers/git-horror-story.html

**Comment by fruiz500** [comment]
This is an excellent suggestion, but my level of knowledge about GitHub doesn't go that far. Perhaps you could point to a tutorial or set of instructions on how to do this?

Many thanks!

**Comment by fruiz500** [comment]
Version 2.1.03 has wholly reorganized code. The JavaScript code is separated from the rest and divided into libraries, which are placed in directories. Code remains fully expanded so people can read it.
